### ISSUE TITLE
Error while runing the Demo server

### ISSUE THREAD

**Issue by khalyl-hamdy** [youssefsharief/arabic-tacotron-tts#1]
when i run the Demo server i get this error and i didn't know how to fix it or what should i do ! 

`Loading checkpoint: ./home/khalyl/Desktop/work/tacotron/arabic-tacotron-tts/model.ckpt-20000
Traceback (most recent call last):
  File "demo_server.py", line 91, in <module>
    synthesizer.load(args.checkpoint)
  File "/home/khalyl/Desktop/work/tacotron/arabic-tacotron-tts/synthesizer.py", line 26, in load
    saver.restore(self.session, checkpoint_path)
  File "/home/khalyl/anaconda3/envs/tacotronenv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1715, in restore
    if not checkpoint_exists(compat.as_text(save_path)):
  File "/home/khalyl/anaconda3/envs/tacotronenv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 2056, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "/home/khalyl/anaconda3/envs/tacotronenv/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "/home/khalyl/anaconda3/envs/tacotronenv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./home/khalyl/Desktop/work/tacotron/arabic-tacotron-tts; No such file or directory
`

**Comment by yoosif0** [comment]
How are you, Khalil,

1. Download and unpack the pretrained model
2. Extract the model files into a folder in a destination of your choice
3. Run the demo server: 
`python demo_server.py --checkpoint .\{folder_in_a_destination_of_your_choice}\model.ckpt-200000`
4. Point your browser at localhost:9200

Have you followed the instructions above?
What command did you use on the command line?
Did you download all dependencies including tensorflow?
