### ISSUE TITLE
Demo Server Error

### ISSUE THREAD

**Issue by firaro** [youssefsharief/arabic-tacotron-tts#14]
I got this error when I invoked py demo_server.py regardless if I included the check point or not.

2021-12-31 02:11:16.182040: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-12-31 02:11:16.182221: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\user\desktop\arabic-tacotron-tts\demo_server.py", line 3, in <module>
    from hparams import hparams, hparams_debug_string
  File "C:\Users\user\desktop\arabic-tacotron-tts\hparams.py", line 5, in <module>
    hparams = tf.contrib.training.HParams(
AttributeError: module 'tensorflow' has no attribute 'contrib'

Do you know what could have gone wrong here?

**Comment by 7atem60010** [comment]
Try downgrading tf to 1.xx.
This worked for me 
!pip install tensorflow==1.15.0
